platform :ios, '10.0'
use_frameworks!

target 'ios-client'
pod 'Alamofire', '4.8.2', :inhibit_warnings => true
pod 'Crashlytics', '3.13.1', :inhibit_warnings => true
pod 'Fabric', '1.10.1', :inhibit_warnings => true
pod 'RealmSwift', '3.15.0', :inhibit_warnings => true
pod 'SVProgressHUD', '2.2.5', :inhibit_warnings => true
pod 'SwiftyJSON', '5.0.0', :inhibit_warnings => true
pod 'SwiftyUserDefaults', '4.0.0', :inhibit_warnings => true
pod 'TangramKit', '1.3.2', :inhibit_warnings => true